# Generated by Django 5.0.2 on 2024-02-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время отправки')),
            ],
            options={
                'verbose_name': 'Письмо от пользователя',
                'verbose_name_plural': 'Письма от пользователей',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время публикации')),
                ('group', models.CharField(choices=[('Fast Food', 'Fast Food'), ('Coffee', 'Coffee'), ('Cocktails', 'Cocktails'), ('Quafe Cake', 'Quafe Cake'), ('Snacks', 'Snacks')], max_length=20, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, upload_to='img/', verbose_name='Картинка')),
                ('q', models.CharField(max_length=20, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Ассортимент',
                'ordering': ('-pub_date',),
            },
        ),
    ]
