# Generated by Django 5.0.2 on 2024-02-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=30, verbose_name='Почта'),
        ),
    ]
