# Generated by Django 5.0.2 on 2024-02-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('group',), 'verbose_name': 'Позиция', 'verbose_name_plural': 'Ассортимент'},
        ),
        migrations.AddField(
            model_name='dish',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_published_main',
            field=models.BooleanField(default=False, verbose_name='На главной странице'),
        ),
    ]
